### ISSUE TITLE
In the documentation retrieve Zhosts from the cluster url

### ISSUE THREAD

**Issue by DavideDelVecchio** [Azure-Samples/hdinsight-kafka-java-get-started#2]
In the documentation the KAFKAZHOSTS shuold be retrieved from the CLUSTER URL 
export KAFKAZKHOSTS=`curl -sS -u admin -G https://$CLUSTERNAME.azurehdinsight.net/api/v1/clusters/$CLUSTERNAME/services/ZOOKEEPER/components/ZOOKEEPER_SERVER | jq -r '["\(.host_components[].HostRoles.host_name):2181"] | join(",")' | cut -d',' -f1,2`
https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-get-started
while here you point to the headnode
export KAFKAZKHOSTS=`curl --silent -u admin:PASSWORD -G http://headnodehost:8080/api/v1/clusters/KAFKANAME/services/ZOOKEEPER/components/ZOOKEEPER_SERVER | jq -r '["\(.host_components[].HostRoles.host_name):2181"] | join(",")'`
The first notation is to the preferred one

**Comment by Blackmist** [comment]
Thanks @DavideDelVecchio , this has been changed in the readme.md.
