### ISSUE TITLE
Topic creation wordcount without the "s"

### ISSUE THREAD

**Issue by embeau** [Azure-Samples/hdinsight-kafka-java-get-started#8]
There is an error in the topic creation command line : /usr/hdp/current/kafka-broker/bin/kafka-topics.sh --create --replication-factor 2 --partitions 8 --topic wordcount --zookeeper $KAFKAZKHOSTS

I think you missed the "s" at the end of "wordcount" ?

**Comment by anushreeringne** [comment]
Thanks a lot.. We fixed it
